/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.systemAdmin;


import GUI.planner.P1_2_JFrame;
import users.JDBC;
import users.User;
import java.util.LinkedList;
import users.*;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import users.systemAdmin.SystemAdmin;
import users.systemAdmin.SystemAdminFactory;

/**
 *
 * @author Grazia  D'Amore
 */
public class SA1_1_JFrame extends javax.swing.JFrame {
    private User admin;
    private JDBC jdbc;
    private Activity.Activities activities;
    private LinkedList<User> added;
    private LinkedList<User> removed;
    /**
     * Creates new form SystemAdminJFrame
     */
    public SA1_1_JFrame(String username, String password) {
        this.admin = new SystemAdminFactory().createUser(username, password);
        this.jdbc = new SystemAdminFactory().createJDBCUser(username, password);
        this.added = new LinkedList<>();
        this.removed = new LinkedList<>();
        this.admin.setActivities(jdbc.loadActivitiesFromDatabase());

        loadUsers();
        initComponents();
        
        this.jLabelName.setText(admin.getUsername()+" ,");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNewPlanner = new javax.swing.JButton();
        jButtonNewMaintainer = new javax.swing.JButton();
        jButtonViewEmployes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButtonNewPlanner.setBackground(new java.awt.Color(153, 153, 153));
        jButtonNewPlanner.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonNewPlanner.setText("New Planner");
        jButtonNewPlanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPlannerActionPerformed(evt);
            }
        });

        jButtonNewMaintainer.setBackground(new java.awt.Color(153, 153, 153));
        jButtonNewMaintainer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonNewMaintainer.setText("New Maintainer");
        jButtonNewMaintainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewMaintainerActionPerformed(evt);
            }
        });

        jButtonViewEmployes.setBackground(new java.awt.Color(153, 153, 153));
        jButtonViewEmployes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonViewEmployes.setText("View Employees");
        jButtonViewEmployes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewEmployesActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hi");

        jLabelName.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("what do you need ? ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("View Activities");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonViewEmployes)
                        .addComponent(jButtonNewMaintainer)
                        .addComponent(jButtonNewPlanner, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonNewPlanner)
                .addGap(28, 28, 28)
                .addComponent(jButtonNewMaintainer)
                .addGap(33, 33, 33)
                .addComponent(jButtonViewEmployes)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewPlannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPlannerActionPerformed
        JTextField username = new JTextField();
        JTextField password = new JPasswordField();
        
        Object[] fields = {
            "Username", username,
            "Password", password
        };
        
        
        int answer = JOptionPane.showConfirmDialog(this, fields, "Insert new Planner", JOptionPane.OK_CANCEL_OPTION);
        
        if (answer == JOptionPane.OK_OPTION){
            while (password.getText().isEmpty()){
                 this.errorMessage("Please insert a password");
                 answer = JOptionPane.showConfirmDialog(this, fields, "Insert new Planner", JOptionPane.OK_CANCEL_OPTION);
            }
            User planner = admin.addUser(username.getText(), password.getText(), AbstractUserFactory.Role.PLANNER); 
            while (planner == null && answer == JOptionPane.OK_OPTION){
                this.errorMessage("This username is already taken");
                answer = JOptionPane.showConfirmDialog(this, fields, "Insert new Planner", JOptionPane.OK_CANCEL_OPTION);
                planner = admin.addUser(username.getText(), password.getText(), AbstractUserFactory.Role.PLANNER);
             }
            if (planner != null)
                added.add(planner);
        }
        
        
    }//GEN-LAST:event_jButtonNewPlannerActionPerformed

    private void jButtonViewEmployesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewEmployesActionPerformed
        if (added != null){ 
            jdbc.saveUsersOnDatabase(added);
        }
        SA1_2_JFrame sa1 = new SA1_2_JFrame(admin);
        sa1.setVisible(true);
    }//GEN-LAST:event_jButtonViewEmployesActionPerformed

    private void jButtonNewMaintainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewMaintainerActionPerformed
        JTextField username = new JTextField();
        JTextField password = new JPasswordField();
        
        Object[] fields = {
            "Username", username,
            "Password", password
        };
        
        int answer = JOptionPane.showConfirmDialog(this, fields, "Insert new Maintainer", JOptionPane.OK_CANCEL_OPTION);
        
        if (answer == JOptionPane.OK_OPTION){
            while (password.getText().isEmpty()){
                this.errorMessage("Please insert a password");
                answer = JOptionPane.showConfirmDialog(this, fields, "Insert new Maintainer", JOptionPane.OK_CANCEL_OPTION);
            }    
            User maintainer = admin.addUser(username.getText(), password.getText(), AbstractUserFactory.Role.MAINTAINER); 
            while (maintainer == null && answer == JOptionPane.OK_OPTION){
               this.errorMessage("This username is already taken");
               answer = JOptionPane.showConfirmDialog(this, fields, "Insert new Maintainer", JOptionPane.OK_CANCEL_OPTION);
               maintainer = admin.addUser(username.getText(), password.getText(), AbstractUserFactory.Role.MAINTAINER);
           }
            if (maintainer != null)
                added.add(maintainer);
        }
    }//GEN-LAST:event_jButtonNewMaintainerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (added != null){ 
            jdbc.saveUsersOnDatabase(added);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        P1_2_JFrame frame = new P1_2_JFrame(admin);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SA1_1_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SA1_1_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SA1_1_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SA1_1_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SA1_1_JFrame("Adam","Kadmon").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNewMaintainer;
    private javax.swing.JButton jButtonNewPlanner;
    private javax.swing.JButton jButtonViewEmployes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables



public void errorMessage(String str){
    JOptionPane.showMessageDialog(this, str, "Ops...", JOptionPane.ERROR_MESSAGE);  
}

public void infoMessage(String str){
    JOptionPane.showMessageDialog(this, str, "Info", JOptionPane.INFORMATION_MESSAGE);
}

public void loadUsers(){ 
    ((SystemAdmin)admin).getUsers().setMaintainers(jdbc.loadMaintainersFromDatabase());
    ((SystemAdmin)admin).getUsers().setPlanners(jdbc.loadPlannersFromDatabase());
}


}