package progettogruppo7.GUI;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import progettogruppo7.Activities;
import progettogruppo7.Activity;
import progettogruppo7.ButtonColumn;
import progettogruppo7.Competence;
import progettogruppo7.Competences;
import progettogruppo7.Planned;
import progettogruppo7.Site;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Francesco Femia
 */
public class ActivitySelection extends javax.swing.JFrame {
    private ButtonColumn bc;
    private DefaultTableModel dtm;
    private DefaultTableCellRenderer cellRenderer;
    private DefaultTableCellRenderer OldRenderer;
    private Activities activities;
    private TableRowSorter<TableModel> sorter;
    /**
     * Creates new form ActivitySelection
     */
    public ActivitySelection(Activities ac) {
        initComponents();
        
        this.setResizable(false);
        
        dtm=(DefaultTableModel)activitySelectionTable.getModel();
        dtm.setRowCount(0);
        dtm.addColumn("Selection");
        activitySelectionTable.getColumnModel().getColumn(3).setMinWidth(130);
        activitySelectionTable.getColumnModel().getColumn(0).setMaxWidth(30);
        
        cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        //cellRenderer.setBackground(Color.ORANGE);
        //cellRenderer.setOpaque(true);
        
        for (int i=0;i<dtm.getColumnCount();i++){
            activitySelectionTable.getColumnModel().getColumn(i).setHeaderRenderer(cellRenderer);
            activitySelectionTable.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
        }
        activitySelectionTable.getColumnModel().getColumn(0).setHeaderValue("ID");
        activitySelectionTable.getColumnModel().getColumn(1).setHeaderValue("Area");
        activitySelectionTable.getColumnModel().getColumn(2).setHeaderValue("Type");
        activitySelectionTable.getColumnModel().getColumn(3).setHeaderValue("Estimated intervention time [min]");
        activitySelectionTable.getColumnModel().getColumn(3);
        
        bc=new ButtonColumn("Select",activitySelectionTable,this.selection,4);
        
        activitySelectionTable.getColumnModel().getColumn(4).setHeaderValue("Selection");
        
        //set the sorting order of the activities by the activity ID
        sorter = new TableRowSorter<TableModel>(activitySelectionTable.getModel());
        activitySelectionTable.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        
        activities=ac;
        
    }
    
    private Action selection = new AbstractAction(){
        public void actionPerformed(ActionEvent e)
        {
            JTable table = (JTable)e.getSource();
            int modelRow = Integer.valueOf( e.getActionCommand() );
            String v=((DefaultTableModel)table.getModel()).getDataVector().elementAt(modelRow).toString();
            String str=v.substring(1, v.length()-2);
            String []s= str.split(",");
            Activity a= activities.getFromActivities(Integer.valueOf(s[0]));
            
            P3_JFrame frame = new P3_JFrame(a);
            frame.setVisible(true);
           // System.out.println(a.toString());
    
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        weekLabel = new javax.swing.JLabel();
        selectionWeek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        activitySelectionTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        weekLabel.setBackground(new java.awt.Color(0, 153, 153));
        weekLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        weekLabel.setForeground(new java.awt.Color(255, 255, 255));
        weekLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weekLabel.setText("Week n°");
        weekLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        weekLabel.setOpaque(true);

        selectionWeek.setBackground(new java.awt.Color(255, 255, 255));
        selectionWeek.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        selectionWeek.setForeground(new java.awt.Color(51, 51, 51));
        selectionWeek.setText("select");
        selectionWeek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectionWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionWeekActionPerformed(evt);
            }
        });

        activitySelectionTable.setBackground(new java.awt.Color(204, 204, 204));
        activitySelectionTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        activitySelectionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        activitySelectionTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        activitySelectionTable.setRowHeight(25);
        jScrollPane1.setViewportView(activitySelectionTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(weekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectionWeek)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectionWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectionWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionWeekActionPerformed
        String answer=JOptionPane.showInputDialog("Select the week");
        
        LinkedList<Integer> weeks=activities.getWeeks();
        if(weeks==null)
            JOptionPane.showMessageDialog(this, "There aren't any activities registered", "Error",JOptionPane.ERROR_MESSAGE );
        else if(weeks.contains(Integer.valueOf(answer))){
            DefaultTableModel tabmod=(DefaultTableModel)activitySelectionTable.getModel();
            tabmod.setRowCount(0);
            for(Activity a: activities.getActivities().values()){
                if(a.getWeek()==Integer.valueOf(answer)){
                    Object []o={a.getActivityID(), a.getSite(), null, a.getEstimatedTime()};
                    tabmod=(DefaultTableModel)activitySelectionTable.getModel();
                    tabmod.addRow(o);
                }

            }
            selectionWeek.setText(answer);
        }
        else
           JOptionPane.showMessageDialog(this, "  The week selected doesn't exist  ", "Error",JOptionPane.ERROR_MESSAGE );
         
            
    }//GEN-LAST:event_selectionWeekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivitySelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivitySelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivitySelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivitySelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Activities activities=new Activities();
        Competences com = new Competences();
        com.insertCompetence(new Competence("Competenza 1"));
        com.insertCompetence(new Competence("Competenza 2"));
        com.insertCompetence(new Competence("Competenza 3"));
        com.insertCompetence(new Competence("Competenza 4"));
        
        Planned p1 =new Planned(1,new Site("Fisciano","Molding"),com,"Manutenzione Generale", 100,true, 1);
        Planned p2 =new Planned(2,new Site("Fisciano","Ombrello"),com,"Manutenzione Generale2", 50,false, 1);
        Planned p3 =new Planned(3,new Site("Baronissi","Molding"),com,"Manutenzione Generale3", 150,true, 3);
        Planned p4 =new Planned(4,new Site("Caserta","Molding"),com,"Manutenzione Generale4", 200,true, 4);
        activities.insertInActivities(p1);
        activities.insertInActivities(p2);
        activities.insertInActivities(p3);
        activities.insertInActivities(p4);
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivitySelection(activities).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable activitySelectionTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectionWeek;
    private javax.swing.JLabel weekLabel;
    // End of variables declaration//GEN-END:variables
}
